"""add_code_to_password_reset_token

Revision ID: ea82047169a7
Revises: a006e695d4af
Create Date: 2025-11-22 19:24:05.213426

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea82047169a7'
down_revision = 'a006e695d4af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('code', sa.String(length=6), nullable=False, server_default='000000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'code')
    # ### end Alembic commands ###

