"""add_language_to_user

Revision ID: a006e695d4af
Revises: 9df2101f1765
Create Date: 2025-11-22 17:34:12.131708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a006e695d4af'
down_revision = '9df2101f1765'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # UserLanguage enum oluştur
    userlanguage_enum = sa.Enum('EN', 'TR', name='userlanguage')
    userlanguage_enum.create(op.get_bind(), checkfirst=True)
    
    # language kolonu ekle (mevcut kullanıcılar için default değer 'EN')
    # NOT NULL olduğu için server_default gerekli
    op.add_column('users', sa.Column('language', userlanguage_enum, nullable=False, server_default=sa.text("'EN'::userlanguage")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # language kolonu kaldır
    op.drop_column('users', 'language')
    
    # UserLanguage enum'u kaldır (eğer başka yerde kullanılmıyorsa)
    userlanguage_enum = sa.Enum(name='userlanguage')
    userlanguage_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

